import{a as b,S as v,i as n}from"./assets/vendor--6n4cVRZ.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))s(o);new MutationObserver(o=>{for(const i of o)if(i.type==="childList")for(const p of i.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&s(p)}).observe(document,{childList:!0,subtree:!0});function r(o){const i={};return o.integrity&&(i.integrity=o.integrity),o.referrerPolicy&&(i.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?i.credentials="include":o.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function s(o){if(o.ep)return;o.ep=!0;const i=r(o);fetch(o.href,i)}})();const w="54669575-c2336e168543ddb8f43b85352",E="https://pixabay.com/api/",y=async(e,t)=>{const r=await b.get(E,{params:{key:w,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}});return console.log(r),r.data},S=new v(".gallery a",{captionsData:"alt",captionDelay:250});function h(e,t){const r=e.map(s=>`
        <li class="gallery-item">
            <a class="gallery-link" href="${s.largeImageURL}">
                <img class="gallery-image" src="${s.webformatURL}" alt="${s.tags}" />
            </a>
            <div class="info">
                <p class="info-item Likes"><b>Likes</b><span>${s.likes}</span></p>
                <p class="info-item"><b>Views</b><span>${s.views}</span></p>
                <p class="info-item"><b>Comments</b><span>${s.comments}</span></p>
                <p class="info-item"><b>Downloads</b><span>${s.downloads}</span></p>
            </div>
        </li>
    `).join("");t.insertAdjacentHTML("beforeend",r),S.refresh()}function q(e){e.innerHTML=""}function u(e,t){t?e.classList.remove("is-hidden"):e.classList.add("is-hidden")}function l(e,{isVisible:t,isLoading:r,isEnd:s}){t!==void 0&&(t?e.classList.remove("is-hidden"):e.classList.add("is-hidden")),r!==void 0&&(e.disabled=r,e.textContent=r?"Loading...":"Load more"),s&&e.classList.add("is-hidden")}const g=document.getElementById("datetime-picker"),H=document.querySelector(".form"),m=document.querySelector(".gallery"),f=document.querySelector(".loader"),a=document.querySelector(".load-more");let c=1;const L=15;let d="";H.addEventListener("submit",async e=>{if(e.preventDefault(),d=g.value.trim(),!d){n.warning({message:"Введіть запит!",position:"topRight"});return}c=1,q(m),l(a,{isVisible:!1}),u(f,!0);try{const t=await y(d,c),r=t.hits,s=t.totalHits;if(r.length===0){n.error({message:"На жаль, за вашим запитом нічого не знайдено.",position:"topRight"});return}h(r,m),g.value="",s>L?l(a,{isVisible:!0,isLoading:!1}):n.info({message:"We're sorry, but you've reached the end of search results."})}catch(t){n.error({message:"Помилка сервера!",position:"topRight"}),console.error(t)}finally{u(f,!1)}});a.addEventListener("click",async()=>{c+=1,u(f,!0),l(a,{isLoading:!0});try{const e=await y(d,c),t=e.hits,r=e.totalHits;h(t,m);const s=document.querySelector(".gallery-item");if(s){const{height:i}=s.getBoundingClientRect();window.scrollBy({top:i*2,behavior:"smooth"})}c*L>=e.totalHits?(l(a,{isEnd:!0}),n.info({message:"We're sorry, but you've reached the end of search results."})):l(a,{isLoading:!1})}catch{n.error({message:"Помилка завантаження!"}),l(a,{isLoading:!1})}finally{u(f,!1)}});
//# sourceMappingURL=index.js.map
