import{a as v,S,i}from"./assets/vendor--6n4cVRZ.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const p of r.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&o(p)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const R="54669575-c2336e168543ddb8f43b85352",q="https://pixabay.com/api/",y=async(e,s)=>{const n=await v.get(q,{params:{key:R,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:s}});return console.log(n),n.data},x=new S(".gallery a",{captionsData:"alt",captionDelay:250});function g(e,s){const n=e.map(o=>`
        <li class="gallery-item">
            <a class="gallery-link" href="${o.largeImageURL}">
                <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}" />
            </a>
            <div class="info">
                <p class="info-item Likes"><b>Likes</b><span>${o.likes}</span></p>
                <p class="info-item"><b>Views</b><span>${o.views}</span></p>
                <p class="info-item"><b>Comments</b><span>${o.comments}</span></p>
                <p class="info-item"><b>Downloads</b><span>${o.downloads}</span></p>
            </div>
        </li>
    `).join("");s.insertAdjacentHTML("beforeend",n),x.refresh()}function B(e){e.innerHTML=""}function h(e){e.style.display="block"}function b(e){e.style.display="none"}function L(e){e.style.display="flex"}function u(e){e.style.display="none"}const m=document.getElementById("datetime-picker"),E=document.querySelector(".form"),f=document.querySelector(".gallery"),d=document.querySelector(".loader"),a=document.querySelector(".load-more");let l=1;const w=15;let c="";E.addEventListener("submit",async e=>{if(e.preventDefault(),c=m.value.trim(),!c){i.warning({message:"Введіть запит!",position:"topRight"});return}l=1,B(f),u(a),h(d);try{const s=await y(c,l),n=s.hits,o=s.totalHits;if(n.length===0){i.error({message:"На жаль, за вашим запитом нічого не знайдено.",position:"topRight"});return}g(n,f),m.value="",o>w?(L(a),a.textContent="Load more"):o>0&&i.info({message:"We're sorry, but you've reached the end of search results."})}catch(s){i.error({message:"Помилка сервера!",position:"topRight"}),console.error(s)}finally{b(d)}});a.addEventListener("click",async()=>{l+=1,h(d),u(a),a.disabled=!0;try{const e=await y(c,l),s=e.hits,n=e.totalHits;g(s,f);const o=document.querySelector(".gallery-item");if(o){const{height:r}=o.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}l>1&&(a.textContent="Fetch more posts");const t=l*w;t>=n?(u(a),i.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter"})):t<n&&L(a)}catch(e){i.error({message:"Помилка сервера!",position:"topRight"}),console.error("Помилка при завантаженні:",e)}finally{b(d),a.disabled=!1}});
//# sourceMappingURL=index.js.map
